//소비자 상품 저장소
export default {
  namespaced: true,
  state: {
    list: [
      {
        id: 0,
        discount: 12,
        count: 1,
        unit: "1단",
        amount: "55kg",
        trans: "택배",
        type: "종이",
        info: "안내 정보",
        category: "채소",
        title: "싱싱한 채소",
        rating: 3.5,
        price: "1000",
        summary: "풀은 맛없어",
        url1: "https://media.istockphoto.com/photos/basket-with-ripe-organic-vegetables-carrot-and-fresh-beetroot-picture-id1175215732",
        url2: "https://cdn.pixabay.com/photo/2016/03/05/19/02/vegetables-1238252_960_720.jpg",
      },
      {
        id: 1,
        discount: 13,
        count: 1,
        unit: "1개",
        amount: "55mg",
        trans: "배달",
        type: "비닐",
        info: "안내 정보",
        category: "과일",
        title: "싱싱한 과일",
        rating: 4,
        price: "2000",
        summary: "달달한 과일",
        url1: "https://media.istockphoto.com/photos/fruit-picture-id185109393?k=20&m=185109393&s=612x612&w=0&h=csJXPTfptltPXa-sZvY0FaSJd9kwUaiw379CARBafkM=",
        url2: "https://media.istockphoto.com/photos/fresh-fruit-and-vegetable-picture-id1206572667?k=20&m=1206572667&s=612x612&w=0&h=0g9kZfFg5FHrf_4mpa7aDthdjJHFcXivUePw6KwTloU=",
      },
      {
        id: 2,
        discount: 14,
        count: 1,
        unit: "1근",
        amount: "55gg",
        trans: "랜덤",
        type: "신발",
        info: "안내 정보",
        category: "고기",
        title: "싱싱한 고기",
        rating: 1,
        price: "25000",
        summary: "육즙가득한 고기",
        url1: "https://cdn.pixabay.com/photo/2016/03/05/23/02/barbecue-1239434__480.jpg",
        url2: "https://cdn.pixabay.com/photo/2014/05/05/19/52/charcuterie-338498__340.jpg",
      },
      {
        id: 3,
        discount: 23,
        count: 1,
        unit: "1명",
        amount: "55tg",
        trans: "박스",
        type: "비밀",
        info: "안내 정보",
        category: "음식",
        title: "싱싱한 음식",
        rating: 5,
        price: "200",
        summary: "맛있는 음식",
        url1: "https://cdn.pixabay.com/photo/2016/09/15/19/24/salad-1672505__340.jpg",
        url2: "https://cdn.pixabay.com/photo/2016/11/23/18/31/pasta-1854245__340.jpg",
      },
      {
        id: 4,
        discount: 42,
        count: 1,
        unit: "1단",
        amount: "55yg",
        trans: "택배",
        type: "랜덤",
        info: "안내 정보",
        category: "채소",
        title: "싱싱한 채소2",
        rating: 3.5,
        price: "1000",
        summary: "채소은 맛없어",
        url1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKjAdQQjICMeKqwTq1DLPo2DfNKXXMGiWZ7Q&usqp=CAU",
        url2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_1zpjVFJUyfxDdIBhPwlgZtjHddLh2vgFBg&usqp=CAU",
      },
      {
        id: 5,
        discount: 22,
        count: 1,
        unit: "1개",
        amount: "55ug",
        trans: "택배",
        type: "몰라",
        info: "안내 정보",
        category: "채소",
        title: "싱싱한 채소3",
        rating: 4,
        price: "2010",
        summary: "달달한 채소",
        url1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVkY7srC7p2460rBzO-ZKm94j8Xr3KH1K1OOX0GKFtCNX0Nk5V74hlgLk6iii5_CyTckM&usqp=CAU",
        url2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCSZA0AeAfJzKeeR79A_tOgnkMwdYrlR2pftCNAI6rH6s1dImSiaQb1Wj6Nw-QNO3v1ns&usqp=CAU",
      },
      {
        id: 6,
        discount: 53,
        count: 1,
        unit: "1근",
        amount: "55ig",
        trans: "택배",
        type: "예시",
        info: "안내 정보",
        category: "채소",
        title: "싱싱한 채소4",
        rating: 1,
        price: "25800",
        summary: "육즙가득한 채소",
        url1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS02DhO94rwCsmtN0aHPANKrRoTPmlANOeQyh59YUjvANMZ9hwOm0TbANd2lLOJV4usJD0&usqp=CAU",
        url2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4QmX9-gbPmNKNum_FeokBmtbupb-URjhxHa5tPfQgOTqxzqF4bbeb9QJIr2acywRsXUc&usqp=CAU",
      },
      {
        id: 7,
        discount: 10,
        count: 1,
        unit: "1명",
        amount: "55og",
        trans: "택배",
        type: "음음",
        info: "안내 정보",
        category: "채소",
        title: "싱싱한 채소5",
        rating: 5,
        price: "2010",
        summary: "맛있는 채소",
        url1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCSdjQyYMf5quGWPefv-nwhu3wWke-0jt7ikPT0E2zZ7buMGLFkBOnyUMdnmOmNSk_Bkw&usqp=CAU",
        url2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJi7R9RN2SEmIgxzX_pQzcCqeEp2otB-kQgSEy-qWWOv_sh18pA7hCekbdQIXPKdny6fs&usqp=CAU",
      },
      {
        id: 8,
        discount: 10,
        count: 1,
        unit: "1가",
        amount: "55qg",
        trans: "택배",
        type: "종이",
        info: "안내 정보",
        category: "채소",
        title: "싱싱한 채소6",
        rating: 3.5,
        price: "110",
        summary: "풀은 맛없어",
        url1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLO_4kY4brDGuX_NDZ2MVIdAGI1NVQOeF2xqUpmIhPuhfUZqJVdpkkDpXg7asdDrZQCSE&usqp=CAU",
        url2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLO_4kY4brDGuX_NDZ2MVIdAGI1NVQOeF2xqUpmIhPuhfUZqJVdpkkDpXg7asdDrZQCSE&usqp=CAU",
      },
      {
        id: 9,
        discount: 10,
        count: 1,
        unit: "1나",
        amount: "55ag",
        trans: "택배",
        type: "종이",
        info: "안내 정보",
        category: "과일",
        title: "싱싱한 과일2",
        rating: 4,
        price: "3000",
        summary: "달달한 과일",
        url1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwKq8j3M8CBpkT0vZxVCuy-NTpuZyBJnDYGrWxGDCx6TMjcVDWJcYNvh6S8wm--JYXaro&usqp=CAU",
        url2: "https://cdn.mkhealth.co.kr/news/photo/202107/53894_55528_5330.jpg",
      },
      {
        id: 10,
        discount: 10,
        count: 1,
        unit: "1다",
        amount: "55zg",
        trans: "택배",
        type: "종이",
        info: "안내 정보",
        category: "과일",
        title: "싱싱한 과일3",
        rating: 1,
        price: "25050",
        summary: "육즙가득한 고기",
        url1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7-QhKgH-q4srMko1zpH-qNMHXnuZvd0hwB4NKv0aSkYedhDwvQhjsPKn_T-lIhF5djVA&usqp=CAU",
        url2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0ZXXp8DdUluxZivd2ZZv_f_l91sPkOaldSOjoU3-Ltoe4jnEjxvHUaOjqA-utOClArlw&usqp=CAU",
      },
      {
        id: 11,
        discount: 10,
        count: 1,
        unit: "1라",
        amount: "55eg",
        trans: "택배",
        type: "종이",
        info: "안내 정보",
        category: "과일",
        title: "싱싱한 과일4",
        rating: 5,
        price: "2001",
        summary: "맛있는 음식",
        url1: "https://thumb.mt.co.kr/06/2020/04/2020040406030375838_1.jpg/dims/optimize/",
        url2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQT_2a_5QX1C01Xhfo1NNb7OiqSjXbpL8oPEUYB9RGjLSr8Efk158gWXyw65OKejoJFzes&usqp=CAU",
      },
      {
        id: 12,
        discount: 10,
        count: 1,
        unit: "1나",
        amount: "55ag",
        trans: "택배",
        type: "종이",
        info: "안내 정보",
        category: "고기",
        title: "싱싱한 고기2",
        rating: 4,
        price: "3000",
        summary: "달달한 과일",
        url1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTWp17y1Wb33vxvTxbVzk8Mb6_SWTVI-14pg&usqp=CAU",
        url2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSedue7mdsGbDz4UzXkUxBI7W8ugvgZnD7ScA&usqp=CAU",
      },
      {
        id: 13,
        discount: 10,
        count: 1,
        unit: "1다",
        amount: "55zg",
        trans: "택배",
        type: "종이",
        info: "안내 정보",
        category: "고기",
        title: "싱싱한 고기3",
        rating: 1,
        price: "25050",
        summary: "육즙가득한 고기",
        url1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSV4DQvkpuveccMqj4VKfoiec2SNacOLPSYOA&usqp=CAU",
        url2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHsKRv6zFRUXKcuH-YbXi28bb2vWqGl9T4ZQ&usqp=CAU",
      },
      {
        id: 14,
        discount: 10,
        count: 1,
        unit: "1라",
        amount: "55eg",
        trans: "택배",
        type: "종이",
        info: "안내 정보",
        category: "고기",
        title: "싱싱한 고기4",
        rating: 5,
        price: "2001",
        summary: "맛있는 음식",
        url1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyF53__oJTk5EM_UC6hmECNbneD8orCnN8Dw&usqp=CAU",
        url2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjmaqUi21CC3-WQOjlAm30B6DkI1-z6HGdXw&usqp=CAU",
      },
      {
        id: 15,
        discount: 10,
        count: 1,
        unit: "1나",
        amount: "55ag",
        trans: "택배",
        type: "종이",
        info: "안내 정보",
        category: "고기",
        title: "싱싱한 고기5",
        rating: 4,
        price: "3000",
        summary: "달달한 과일",
        url1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlYNvcnXsxflqu7bVESPmzR-eM7xa_JuuwJM-y7S2igeFlZNwE7DkM7TmWi2ToRlAEDZU&usqp=CAU",
        url2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvfR9czd0woCGi3lQTLdYMu9KnOb9DMMlfMA&usqp=CAU",
      },
      {
        id: 16,
        discount: 10,
        count: 1,
        unit: "1다",
        amount: "55zg",
        trans: "택배",
        type: "종이",
        info: "안내 정보",
        category: "고기",
        title: "싱싱한 고기6",
        rating: 1,
        price: "25050",
        summary: "육즙가득한 고기",
        url1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlYNvcnXsxflqu7bVESPmzR-eM7xa_JuuwJM-y7S2igeFlZNwE7DkM7TmWi2ToRlAEDZU&usqp=CAU",
        url2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAhrjhPXVFYW-ShsKlhPl3dexltAFhFWJG_A&usqp=CAU",
      },
      {
        id: 17,
        discount: 10,
        count: 1,
        unit: "1라",
        amount: "55eg",
        trans: "택배",
        type: "종이",
        info: "안내 정보",
        category: "고기",
        title: "싱싱한 고기7",
        rating: 5,
        price: "2001",
        summary: "맛있는 음식",
        url1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFqOKcv6qJb_Or06_r5VD2N0lbQHQfv0ItHajDsd3QMJXpXj2ZtEtmBoYeG1tHj2IPMEA&usqp=CAU",
        url2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEDQvpMhi38hgW6jeSnW-trGF6LFX5RnOOSw&usqp=CAU",
      },
    ],
    showList: [],
    length: null,
    searchList: [],
  },
  mutations: {
    pagination(state, page) {
      //상품 리스트 페이징 처리
      const toss = [...state.list];
      const paging = page - 1;
      state.length = Math.ceil(state.list.length / 4);
      state.showList = toss.splice(paging * 4, 4);
    },
    packageSearch(state, findItem) {
      //패키지 메뉴 상품 검색
      state.searchList = [];
      findItem.forEach((val, idx) => {
        if (val == null) console.log("비어있습니다.");
        else {
          const toss = state.list.filter((item) => item.category === val);
          state.searchList.splice(idx, 0, toss);
        }
      });
    },
    deleteAll(state) {
      state.searchList = [];
    },
  },
  actions: {
    pagination(context, payload) {
      context.commit("pagination", payload);
    },
    packageSearch(context, payload) {
      context.commit("packageSearch", payload);
    },
  },
};
